extend = [
    { path = "../cargo-make/main.toml" },
    { path = "../cargo-make/cargo-leptos-webdriver-test.toml" },
]

[env]
CLIENT_PROCESS_NAME = "todo_app_sqlite_axum"

[tasks.test-ui]
cwd = "./end2end"
command = "cargo"
args = ["make", "test-ui", "${@}"]
